const CourseData = [
    {
        id:1,
        title: "Storytelling for Project Pitching",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "true",
    },
    {
        id:2,
        title: "Storytelling for Project Pitching",
        category1: "IT",
        category2: "Buiness",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "true",
    },
    {
        id:3,
        title: "Storytelling for Project Pitching",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "true",
    },
    {
        id:4,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "true",
    },
    //////////////////
    {
        id:5,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "true",
    },
    {
        id:6,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "true",
    },
    {
        id:7,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "true",
    },
    {
        id:8,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "true",
    },
    //////////////////
    {
        id:9,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:10,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:11,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:12,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:13,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:14,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:15,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:16,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:17,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:18,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    ///////////////////////
    {
        id:19,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
        new: "true",
    },
    {
        id:20,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
        new: "true",
    },
    {
        id:21,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
        new: "true",
    },
    {
        id:22,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: 2.5,
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "online",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
        new: "true",
    },
    ///////////////////
    {
        id:23,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:24,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:25,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:26,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:27,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:28,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:29,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:30,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:31,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    {
        id:32,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
    },
    ///////////////////////
    {
        id:33,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
        new: "true",
    },
    {
        id:34,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
        new: "true",
    },
    {
        id:35,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
        new: "true",
    },
    {
        id:36,
        title: "Google Workspace (G Suite) Admin - The Complete Course",
        category1: "IT",
        category2: "Business",
        people: 2800,
        time: "09.00 - 17.00 น.",
        rating: 4,
        teacher: "Nuttapon Hankamolsiri",
        courseType: "classroom",
        season: "รุ่นที่ 1",
        duration: "12 Dec 2020 - 13 Dec 2020",
        place:"True Digital Park, Starbucks Meeting room Floor 1st",
        img: "https://image.freepik.com/free-vector/gradient-geometric-background_52683-54352.jpg",
        hot: "false",
        new: "true",
    },
];

    export default CourseData;
    