const MyTeamData = [
    {
        id:1,
        name: "Nuttapon Hankamolsiri",
        position: "Developer", 
        department: "HR",
        Dialogue: "complete",
        IDPs: "inProgress",
        PL: "SL4",
        img: "https://image.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg",
    },
    {
        id:2,
        name: "Nuttapon Hankamolsiri",
        position: "Developer", 
        department: "HR",
        Dialogue: "incomplete",
        IDPs: "inProgress",
        PL: "SL4",
        img: "https://image.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg",
    },
    {
        id:3,
        name: "Nuttapon Hankamolsiri",
        position: "Developer", 
        department: "HR",
        Dialogue: "complete",
        IDPs: "inProgress",
        PL: "SL4",
        img: "https://image.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg",
    },
    {
        id:4,
        name: "Nuttapon Hankamolsiri",
        position: "Developer", 
        department: "HR",
        Dialogue: "incomplete",
        IDPs: "inProgress",
        PL: "SL4",
        img: "https://image.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg",
    },
    //////////////////
    {
        id:5,
        name: "Nuttapon Hankamolsiri",
        position: "Developer", 
        department: "HR",
        Dialogue: "complete",
        IDPs: "inProgress",
        PL: "SL4",
        img: "https://image.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg",
    },
    {
        id:6,
        name: "Nuttapon Hankamolsiri",
        position: "Developer", 
        department: "HR",
        Dialogue: "complete",
        IDPs: "incomplete",
        PL: "SL4",
        img: "https://image.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg",
    },
    {
        id:7,
        name: "Nuttapon Hankamolsiri",
        position: "Developer", 
        department: "HR",
        Dialogue: "complete",
        IDPs: "inProgress",
        PL: "SL4",
        img: "https://image.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg",
    },
    {
        id:8,
        name: "Nuttapon Hankamolsiri",
        position: "Developer", 
        department: "HR",
        Dialogue: "incomplete",
        IDPs: "inProgress",
        PL: "SL4",
        img: "https://image.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg",
    },
    //////////////////
];

export default MyTeamData;
    